// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package gqlclient

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// __createDeviceInput is used internally by genqlient
type __createDeviceInput struct {
	Token           string `json:"token"`
	DeviceTypeToken string `json:"deviceTypeToken"`
	Name            string `json:"name"`
	Description     string `json:"description"`
	Metadata        string `json:"metadata"`
}

// GetToken returns __createDeviceInput.Token, and is useful for accessing the field via an interface.
func (v *__createDeviceInput) GetToken() string { return v.Token }

// GetDeviceTypeToken returns __createDeviceInput.DeviceTypeToken, and is useful for accessing the field via an interface.
func (v *__createDeviceInput) GetDeviceTypeToken() string { return v.DeviceTypeToken }

// GetName returns __createDeviceInput.Name, and is useful for accessing the field via an interface.
func (v *__createDeviceInput) GetName() string { return v.Name }

// GetDescription returns __createDeviceInput.Description, and is useful for accessing the field via an interface.
func (v *__createDeviceInput) GetDescription() string { return v.Description }

// GetMetadata returns __createDeviceInput.Metadata, and is useful for accessing the field via an interface.
func (v *__createDeviceInput) GetMetadata() string { return v.Metadata }

// __createDeviceRelationshipInput is used internally by genqlient
type __createDeviceRelationshipInput struct {
	Token            string `json:"token"`
	SourceDevice     string `json:"sourceDevice"`
	TargetDevice     string `json:"targetDevice"`
	RelationshipType string `json:"relationshipType"`
}

// GetToken returns __createDeviceRelationshipInput.Token, and is useful for accessing the field via an interface.
func (v *__createDeviceRelationshipInput) GetToken() string { return v.Token }

// GetSourceDevice returns __createDeviceRelationshipInput.SourceDevice, and is useful for accessing the field via an interface.
func (v *__createDeviceRelationshipInput) GetSourceDevice() string { return v.SourceDevice }

// GetTargetDevice returns __createDeviceRelationshipInput.TargetDevice, and is useful for accessing the field via an interface.
func (v *__createDeviceRelationshipInput) GetTargetDevice() string { return v.TargetDevice }

// GetRelationshipType returns __createDeviceRelationshipInput.RelationshipType, and is useful for accessing the field via an interface.
func (v *__createDeviceRelationshipInput) GetRelationshipType() string { return v.RelationshipType }

// __createDeviceRelationshipTypeInput is used internally by genqlient
type __createDeviceRelationshipTypeInput struct {
	Token       string `json:"token"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Metadata    string `json:"metadata"`
}

// GetToken returns __createDeviceRelationshipTypeInput.Token, and is useful for accessing the field via an interface.
func (v *__createDeviceRelationshipTypeInput) GetToken() string { return v.Token }

// GetName returns __createDeviceRelationshipTypeInput.Name, and is useful for accessing the field via an interface.
func (v *__createDeviceRelationshipTypeInput) GetName() string { return v.Name }

// GetDescription returns __createDeviceRelationshipTypeInput.Description, and is useful for accessing the field via an interface.
func (v *__createDeviceRelationshipTypeInput) GetDescription() string { return v.Description }

// GetMetadata returns __createDeviceRelationshipTypeInput.Metadata, and is useful for accessing the field via an interface.
func (v *__createDeviceRelationshipTypeInput) GetMetadata() string { return v.Metadata }

// __createDeviceTypeInput is used internally by genqlient
type __createDeviceTypeInput struct {
	Token           string `json:"token"`
	Name            string `json:"name"`
	Description     string `json:"description"`
	ImageUrl        string `json:"imageUrl"`
	Icon            string `json:"icon"`
	BackgroundColor string `json:"backgroundColor"`
	ForegroundColor string `json:"foregroundColor"`
	BorderColor     string `json:"borderColor"`
	Metadata        string `json:"metadata"`
}

// GetToken returns __createDeviceTypeInput.Token, and is useful for accessing the field via an interface.
func (v *__createDeviceTypeInput) GetToken() string { return v.Token }

// GetName returns __createDeviceTypeInput.Name, and is useful for accessing the field via an interface.
func (v *__createDeviceTypeInput) GetName() string { return v.Name }

// GetDescription returns __createDeviceTypeInput.Description, and is useful for accessing the field via an interface.
func (v *__createDeviceTypeInput) GetDescription() string { return v.Description }

// GetImageUrl returns __createDeviceTypeInput.ImageUrl, and is useful for accessing the field via an interface.
func (v *__createDeviceTypeInput) GetImageUrl() string { return v.ImageUrl }

// GetIcon returns __createDeviceTypeInput.Icon, and is useful for accessing the field via an interface.
func (v *__createDeviceTypeInput) GetIcon() string { return v.Icon }

// GetBackgroundColor returns __createDeviceTypeInput.BackgroundColor, and is useful for accessing the field via an interface.
func (v *__createDeviceTypeInput) GetBackgroundColor() string { return v.BackgroundColor }

// GetForegroundColor returns __createDeviceTypeInput.ForegroundColor, and is useful for accessing the field via an interface.
func (v *__createDeviceTypeInput) GetForegroundColor() string { return v.ForegroundColor }

// GetBorderColor returns __createDeviceTypeInput.BorderColor, and is useful for accessing the field via an interface.
func (v *__createDeviceTypeInput) GetBorderColor() string { return v.BorderColor }

// GetMetadata returns __createDeviceTypeInput.Metadata, and is useful for accessing the field via an interface.
func (v *__createDeviceTypeInput) GetMetadata() string { return v.Metadata }

// __getDeviceByTokenInput is used internally by genqlient
type __getDeviceByTokenInput struct {
	Token string `json:"token"`
}

// GetToken returns __getDeviceByTokenInput.Token, and is useful for accessing the field via an interface.
func (v *__getDeviceByTokenInput) GetToken() string { return v.Token }

// __getDeviceRelationshipByTokenInput is used internally by genqlient
type __getDeviceRelationshipByTokenInput struct {
	Token string `json:"token"`
}

// GetToken returns __getDeviceRelationshipByTokenInput.Token, and is useful for accessing the field via an interface.
func (v *__getDeviceRelationshipByTokenInput) GetToken() string { return v.Token }

// __getDeviceRelationshipTypeByTokenInput is used internally by genqlient
type __getDeviceRelationshipTypeByTokenInput struct {
	Token string `json:"token"`
}

// GetToken returns __getDeviceRelationshipTypeByTokenInput.Token, and is useful for accessing the field via an interface.
func (v *__getDeviceRelationshipTypeByTokenInput) GetToken() string { return v.Token }

// __getDeviceTypeByTokenInput is used internally by genqlient
type __getDeviceTypeByTokenInput struct {
	Token string `json:"token"`
}

// GetToken returns __getDeviceTypeByTokenInput.Token, and is useful for accessing the field via an interface.
func (v *__getDeviceTypeByTokenInput) GetToken() string { return v.Token }

// __listDeviceRelationshipTypesInput is used internally by genqlient
type __listDeviceRelationshipTypesInput struct {
	PageNumber int `json:"pageNumber"`
	PageSize   int `json:"pageSize"`
}

// GetPageNumber returns __listDeviceRelationshipTypesInput.PageNumber, and is useful for accessing the field via an interface.
func (v *__listDeviceRelationshipTypesInput) GetPageNumber() int { return v.PageNumber }

// GetPageSize returns __listDeviceRelationshipTypesInput.PageSize, and is useful for accessing the field via an interface.
func (v *__listDeviceRelationshipTypesInput) GetPageSize() int { return v.PageSize }

// __listDeviceRelationshipsInput is used internally by genqlient
type __listDeviceRelationshipsInput struct {
	PageNumber int `json:"pageNumber"`
	PageSize   int `json:"pageSize"`
}

// GetPageNumber returns __listDeviceRelationshipsInput.PageNumber, and is useful for accessing the field via an interface.
func (v *__listDeviceRelationshipsInput) GetPageNumber() int { return v.PageNumber }

// GetPageSize returns __listDeviceRelationshipsInput.PageSize, and is useful for accessing the field via an interface.
func (v *__listDeviceRelationshipsInput) GetPageSize() int { return v.PageSize }

// __listDeviceTypesInput is used internally by genqlient
type __listDeviceTypesInput struct {
	PageNumber int `json:"pageNumber"`
	PageSize   int `json:"pageSize"`
}

// GetPageNumber returns __listDeviceTypesInput.PageNumber, and is useful for accessing the field via an interface.
func (v *__listDeviceTypesInput) GetPageNumber() int { return v.PageNumber }

// GetPageSize returns __listDeviceTypesInput.PageSize, and is useful for accessing the field via an interface.
func (v *__listDeviceTypesInput) GetPageSize() int { return v.PageSize }

// __listDevicesInput is used internally by genqlient
type __listDevicesInput struct {
	PageNumber int `json:"pageNumber"`
	PageSize   int `json:"pageSize"`
}

// GetPageNumber returns __listDevicesInput.PageNumber, and is useful for accessing the field via an interface.
func (v *__listDevicesInput) GetPageNumber() int { return v.PageNumber }

// GetPageSize returns __listDevicesInput.PageSize, and is useful for accessing the field via an interface.
func (v *__listDevicesInput) GetPageSize() int { return v.PageSize }

// createDeviceCreateDevice includes the requested fields of the GraphQL type Device.
type createDeviceCreateDevice struct {
	Id    string `json:"id"`
	Token string `json:"token"`
}

// GetId returns createDeviceCreateDevice.Id, and is useful for accessing the field via an interface.
func (v *createDeviceCreateDevice) GetId() string { return v.Id }

// GetToken returns createDeviceCreateDevice.Token, and is useful for accessing the field via an interface.
func (v *createDeviceCreateDevice) GetToken() string { return v.Token }

// createDeviceRelationshipCreateDeviceRelationship includes the requested fields of the GraphQL type DeviceRelationship.
type createDeviceRelationshipCreateDeviceRelationship struct {
	Id    string `json:"id"`
	Token string `json:"token"`
}

// GetId returns createDeviceRelationshipCreateDeviceRelationship.Id, and is useful for accessing the field via an interface.
func (v *createDeviceRelationshipCreateDeviceRelationship) GetId() string { return v.Id }

// GetToken returns createDeviceRelationshipCreateDeviceRelationship.Token, and is useful for accessing the field via an interface.
func (v *createDeviceRelationshipCreateDeviceRelationship) GetToken() string { return v.Token }

// createDeviceRelationshipResponse is returned by createDeviceRelationship on success.
type createDeviceRelationshipResponse struct {
	CreateDeviceRelationship createDeviceRelationshipCreateDeviceRelationship `json:"createDeviceRelationship"`
}

// GetCreateDeviceRelationship returns createDeviceRelationshipResponse.CreateDeviceRelationship, and is useful for accessing the field via an interface.
func (v *createDeviceRelationshipResponse) GetCreateDeviceRelationship() createDeviceRelationshipCreateDeviceRelationship {
	return v.CreateDeviceRelationship
}

// createDeviceRelationshipTypeCreateDeviceRelationshipType includes the requested fields of the GraphQL type DeviceRelationshipType.
type createDeviceRelationshipTypeCreateDeviceRelationshipType struct {
	Id    string `json:"id"`
	Token string `json:"token"`
}

// GetId returns createDeviceRelationshipTypeCreateDeviceRelationshipType.Id, and is useful for accessing the field via an interface.
func (v *createDeviceRelationshipTypeCreateDeviceRelationshipType) GetId() string { return v.Id }

// GetToken returns createDeviceRelationshipTypeCreateDeviceRelationshipType.Token, and is useful for accessing the field via an interface.
func (v *createDeviceRelationshipTypeCreateDeviceRelationshipType) GetToken() string { return v.Token }

// createDeviceRelationshipTypeResponse is returned by createDeviceRelationshipType on success.
type createDeviceRelationshipTypeResponse struct {
	CreateDeviceRelationshipType createDeviceRelationshipTypeCreateDeviceRelationshipType `json:"createDeviceRelationshipType"`
}

// GetCreateDeviceRelationshipType returns createDeviceRelationshipTypeResponse.CreateDeviceRelationshipType, and is useful for accessing the field via an interface.
func (v *createDeviceRelationshipTypeResponse) GetCreateDeviceRelationshipType() createDeviceRelationshipTypeCreateDeviceRelationshipType {
	return v.CreateDeviceRelationshipType
}

// createDeviceResponse is returned by createDevice on success.
type createDeviceResponse struct {
	CreateDevice createDeviceCreateDevice `json:"createDevice"`
}

// GetCreateDevice returns createDeviceResponse.CreateDevice, and is useful for accessing the field via an interface.
func (v *createDeviceResponse) GetCreateDevice() createDeviceCreateDevice { return v.CreateDevice }

// createDeviceTypeCreateDeviceType includes the requested fields of the GraphQL type DeviceType.
type createDeviceTypeCreateDeviceType struct {
	Id    string `json:"id"`
	Token string `json:"token"`
}

// GetId returns createDeviceTypeCreateDeviceType.Id, and is useful for accessing the field via an interface.
func (v *createDeviceTypeCreateDeviceType) GetId() string { return v.Id }

// GetToken returns createDeviceTypeCreateDeviceType.Token, and is useful for accessing the field via an interface.
func (v *createDeviceTypeCreateDeviceType) GetToken() string { return v.Token }

// createDeviceTypeResponse is returned by createDeviceType on success.
type createDeviceTypeResponse struct {
	CreateDeviceType createDeviceTypeCreateDeviceType `json:"createDeviceType"`
}

// GetCreateDeviceType returns createDeviceTypeResponse.CreateDeviceType, and is useful for accessing the field via an interface.
func (v *createDeviceTypeResponse) GetCreateDeviceType() createDeviceTypeCreateDeviceType {
	return v.CreateDeviceType
}

// getDeviceByTokenDeviceByTokenDevice includes the requested fields of the GraphQL type Device.
type getDeviceByTokenDeviceByTokenDevice struct {
	Id                string                                                                 `json:"id"`
	CreatedAt         string                                                                 `json:"createdAt"`
	UpdatedAt         string                                                                 `json:"updatedAt"`
	DeletedAt         string                                                                 `json:"deletedAt"`
	Token             string                                                                 `json:"token"`
	Name              string                                                                 `json:"name"`
	Description       string                                                                 `json:"description"`
	DeviceType        getDeviceByTokenDeviceByTokenDeviceDeviceType                          `json:"deviceType"`
	ActiveAssignments []getDeviceByTokenDeviceByTokenDeviceActiveAssignmentsDeviceAssignment `json:"activeAssignments"`
	Metadata          string                                                                 `json:"metadata"`
}

// GetId returns getDeviceByTokenDeviceByTokenDevice.Id, and is useful for accessing the field via an interface.
func (v *getDeviceByTokenDeviceByTokenDevice) GetId() string { return v.Id }

// GetCreatedAt returns getDeviceByTokenDeviceByTokenDevice.CreatedAt, and is useful for accessing the field via an interface.
func (v *getDeviceByTokenDeviceByTokenDevice) GetCreatedAt() string { return v.CreatedAt }

// GetUpdatedAt returns getDeviceByTokenDeviceByTokenDevice.UpdatedAt, and is useful for accessing the field via an interface.
func (v *getDeviceByTokenDeviceByTokenDevice) GetUpdatedAt() string { return v.UpdatedAt }

// GetDeletedAt returns getDeviceByTokenDeviceByTokenDevice.DeletedAt, and is useful for accessing the field via an interface.
func (v *getDeviceByTokenDeviceByTokenDevice) GetDeletedAt() string { return v.DeletedAt }

// GetToken returns getDeviceByTokenDeviceByTokenDevice.Token, and is useful for accessing the field via an interface.
func (v *getDeviceByTokenDeviceByTokenDevice) GetToken() string { return v.Token }

// GetName returns getDeviceByTokenDeviceByTokenDevice.Name, and is useful for accessing the field via an interface.
func (v *getDeviceByTokenDeviceByTokenDevice) GetName() string { return v.Name }

// GetDescription returns getDeviceByTokenDeviceByTokenDevice.Description, and is useful for accessing the field via an interface.
func (v *getDeviceByTokenDeviceByTokenDevice) GetDescription() string { return v.Description }

// GetDeviceType returns getDeviceByTokenDeviceByTokenDevice.DeviceType, and is useful for accessing the field via an interface.
func (v *getDeviceByTokenDeviceByTokenDevice) GetDeviceType() getDeviceByTokenDeviceByTokenDeviceDeviceType {
	return v.DeviceType
}

// GetActiveAssignments returns getDeviceByTokenDeviceByTokenDevice.ActiveAssignments, and is useful for accessing the field via an interface.
func (v *getDeviceByTokenDeviceByTokenDevice) GetActiveAssignments() []getDeviceByTokenDeviceByTokenDeviceActiveAssignmentsDeviceAssignment {
	return v.ActiveAssignments
}

// GetMetadata returns getDeviceByTokenDeviceByTokenDevice.Metadata, and is useful for accessing the field via an interface.
func (v *getDeviceByTokenDeviceByTokenDevice) GetMetadata() string { return v.Metadata }

// getDeviceByTokenDeviceByTokenDeviceActiveAssignmentsDeviceAssignment includes the requested fields of the GraphQL type DeviceAssignment.
type getDeviceByTokenDeviceByTokenDeviceActiveAssignmentsDeviceAssignment struct {
	Token string `json:"token"`
}

// GetToken returns getDeviceByTokenDeviceByTokenDeviceActiveAssignmentsDeviceAssignment.Token, and is useful for accessing the field via an interface.
func (v *getDeviceByTokenDeviceByTokenDeviceActiveAssignmentsDeviceAssignment) GetToken() string {
	return v.Token
}

// getDeviceByTokenDeviceByTokenDeviceDeviceType includes the requested fields of the GraphQL type DeviceType.
type getDeviceByTokenDeviceByTokenDeviceDeviceType struct {
	Token       string `json:"token"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

// GetToken returns getDeviceByTokenDeviceByTokenDeviceDeviceType.Token, and is useful for accessing the field via an interface.
func (v *getDeviceByTokenDeviceByTokenDeviceDeviceType) GetToken() string { return v.Token }

// GetName returns getDeviceByTokenDeviceByTokenDeviceDeviceType.Name, and is useful for accessing the field via an interface.
func (v *getDeviceByTokenDeviceByTokenDeviceDeviceType) GetName() string { return v.Name }

// GetDescription returns getDeviceByTokenDeviceByTokenDeviceDeviceType.Description, and is useful for accessing the field via an interface.
func (v *getDeviceByTokenDeviceByTokenDeviceDeviceType) GetDescription() string { return v.Description }

// getDeviceByTokenResponse is returned by getDeviceByToken on success.
type getDeviceByTokenResponse struct {
	DeviceByToken getDeviceByTokenDeviceByTokenDevice `json:"deviceByToken"`
}

// GetDeviceByToken returns getDeviceByTokenResponse.DeviceByToken, and is useful for accessing the field via an interface.
func (v *getDeviceByTokenResponse) GetDeviceByToken() getDeviceByTokenDeviceByTokenDevice {
	return v.DeviceByToken
}

// getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationship includes the requested fields of the GraphQL type DeviceRelationship.
type getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationship struct {
	Id               string                                                                                                        `json:"id"`
	CreatedAt        string                                                                                                        `json:"createdAt"`
	UpdatedAt        string                                                                                                        `json:"updatedAt"`
	DeletedAt        string                                                                                                        `json:"deletedAt"`
	Token            string                                                                                                        `json:"token"`
	SourceDevice     getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipSourceDevice                           `json:"sourceDevice"`
	TargetDevice     getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipTargetDevice                           `json:"targetDevice"`
	RelationshipType getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipRelationshipTypeDeviceRelationshipType `json:"relationshipType"`
	Metadata         string                                                                                                        `json:"metadata"`
}

// GetId returns getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationship.Id, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationship) GetId() string {
	return v.Id
}

// GetCreatedAt returns getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationship.CreatedAt, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationship) GetCreatedAt() string {
	return v.CreatedAt
}

// GetUpdatedAt returns getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationship.UpdatedAt, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationship) GetUpdatedAt() string {
	return v.UpdatedAt
}

// GetDeletedAt returns getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationship.DeletedAt, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationship) GetDeletedAt() string {
	return v.DeletedAt
}

// GetToken returns getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationship.Token, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationship) GetToken() string {
	return v.Token
}

// GetSourceDevice returns getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationship.SourceDevice, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationship) GetSourceDevice() getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipSourceDevice {
	return v.SourceDevice
}

// GetTargetDevice returns getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationship.TargetDevice, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationship) GetTargetDevice() getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipTargetDevice {
	return v.TargetDevice
}

// GetRelationshipType returns getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationship.RelationshipType, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationship) GetRelationshipType() getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipRelationshipTypeDeviceRelationshipType {
	return v.RelationshipType
}

// GetMetadata returns getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationship.Metadata, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationship) GetMetadata() string {
	return v.Metadata
}

// getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipRelationshipTypeDeviceRelationshipType includes the requested fields of the GraphQL type DeviceRelationshipType.
type getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipRelationshipTypeDeviceRelationshipType struct {
	Token       string `json:"token"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

// GetToken returns getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipRelationshipTypeDeviceRelationshipType.Token, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipRelationshipTypeDeviceRelationshipType) GetToken() string {
	return v.Token
}

// GetName returns getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipRelationshipTypeDeviceRelationshipType.Name, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipRelationshipTypeDeviceRelationshipType) GetName() string {
	return v.Name
}

// GetDescription returns getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipRelationshipTypeDeviceRelationshipType.Description, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipRelationshipTypeDeviceRelationshipType) GetDescription() string {
	return v.Description
}

// getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipSourceDevice includes the requested fields of the GraphQL type Device.
type getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipSourceDevice struct {
	Token       string `json:"token"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

// GetToken returns getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipSourceDevice.Token, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipSourceDevice) GetToken() string {
	return v.Token
}

// GetName returns getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipSourceDevice.Name, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipSourceDevice) GetName() string {
	return v.Name
}

// GetDescription returns getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipSourceDevice.Description, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipSourceDevice) GetDescription() string {
	return v.Description
}

// getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipTargetDevice includes the requested fields of the GraphQL type Device.
type getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipTargetDevice struct {
	Token       string `json:"token"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

// GetToken returns getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipTargetDevice.Token, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipTargetDevice) GetToken() string {
	return v.Token
}

// GetName returns getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipTargetDevice.Name, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipTargetDevice) GetName() string {
	return v.Name
}

// GetDescription returns getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipTargetDevice.Description, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationshipTargetDevice) GetDescription() string {
	return v.Description
}

// getDeviceRelationshipByTokenResponse is returned by getDeviceRelationshipByToken on success.
type getDeviceRelationshipByTokenResponse struct {
	DeviceRelationshipByToken getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationship `json:"deviceRelationshipByToken"`
}

// GetDeviceRelationshipByToken returns getDeviceRelationshipByTokenResponse.DeviceRelationshipByToken, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipByTokenResponse) GetDeviceRelationshipByToken() getDeviceRelationshipByTokenDeviceRelationshipByTokenDeviceRelationship {
	return v.DeviceRelationshipByToken
}

// getDeviceRelationshipTypeByTokenDeviceRelationshipTypeByTokenDeviceRelationshipType includes the requested fields of the GraphQL type DeviceRelationshipType.
type getDeviceRelationshipTypeByTokenDeviceRelationshipTypeByTokenDeviceRelationshipType struct {
	Id          string `json:"id"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
	DeletedAt   string `json:"deletedAt"`
	Token       string `json:"token"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Metadata    string `json:"metadata"`
}

// GetId returns getDeviceRelationshipTypeByTokenDeviceRelationshipTypeByTokenDeviceRelationshipType.Id, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipTypeByTokenDeviceRelationshipTypeByTokenDeviceRelationshipType) GetId() string {
	return v.Id
}

// GetCreatedAt returns getDeviceRelationshipTypeByTokenDeviceRelationshipTypeByTokenDeviceRelationshipType.CreatedAt, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipTypeByTokenDeviceRelationshipTypeByTokenDeviceRelationshipType) GetCreatedAt() string {
	return v.CreatedAt
}

// GetUpdatedAt returns getDeviceRelationshipTypeByTokenDeviceRelationshipTypeByTokenDeviceRelationshipType.UpdatedAt, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipTypeByTokenDeviceRelationshipTypeByTokenDeviceRelationshipType) GetUpdatedAt() string {
	return v.UpdatedAt
}

// GetDeletedAt returns getDeviceRelationshipTypeByTokenDeviceRelationshipTypeByTokenDeviceRelationshipType.DeletedAt, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipTypeByTokenDeviceRelationshipTypeByTokenDeviceRelationshipType) GetDeletedAt() string {
	return v.DeletedAt
}

// GetToken returns getDeviceRelationshipTypeByTokenDeviceRelationshipTypeByTokenDeviceRelationshipType.Token, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipTypeByTokenDeviceRelationshipTypeByTokenDeviceRelationshipType) GetToken() string {
	return v.Token
}

// GetName returns getDeviceRelationshipTypeByTokenDeviceRelationshipTypeByTokenDeviceRelationshipType.Name, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipTypeByTokenDeviceRelationshipTypeByTokenDeviceRelationshipType) GetName() string {
	return v.Name
}

// GetDescription returns getDeviceRelationshipTypeByTokenDeviceRelationshipTypeByTokenDeviceRelationshipType.Description, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipTypeByTokenDeviceRelationshipTypeByTokenDeviceRelationshipType) GetDescription() string {
	return v.Description
}

// GetMetadata returns getDeviceRelationshipTypeByTokenDeviceRelationshipTypeByTokenDeviceRelationshipType.Metadata, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipTypeByTokenDeviceRelationshipTypeByTokenDeviceRelationshipType) GetMetadata() string {
	return v.Metadata
}

// getDeviceRelationshipTypeByTokenResponse is returned by getDeviceRelationshipTypeByToken on success.
type getDeviceRelationshipTypeByTokenResponse struct {
	DeviceRelationshipTypeByToken getDeviceRelationshipTypeByTokenDeviceRelationshipTypeByTokenDeviceRelationshipType `json:"deviceRelationshipTypeByToken"`
}

// GetDeviceRelationshipTypeByToken returns getDeviceRelationshipTypeByTokenResponse.DeviceRelationshipTypeByToken, and is useful for accessing the field via an interface.
func (v *getDeviceRelationshipTypeByTokenResponse) GetDeviceRelationshipTypeByToken() getDeviceRelationshipTypeByTokenDeviceRelationshipTypeByTokenDeviceRelationshipType {
	return v.DeviceRelationshipTypeByToken
}

// getDeviceTypeByTokenDeviceTypeByTokenDeviceType includes the requested fields of the GraphQL type DeviceType.
type getDeviceTypeByTokenDeviceTypeByTokenDeviceType struct {
	Id              string `json:"id"`
	CreatedAt       string `json:"createdAt"`
	UpdatedAt       string `json:"updatedAt"`
	DeletedAt       string `json:"deletedAt"`
	Token           string `json:"token"`
	Name            string `json:"name"`
	Description     string `json:"description"`
	ImageUrl        string `json:"imageUrl"`
	Icon            string `json:"icon"`
	BackgroundColor string `json:"backgroundColor"`
	ForegroundColor string `json:"foregroundColor"`
	BorderColor     string `json:"borderColor"`
	Metadata        string `json:"metadata"`
}

// GetId returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.Id, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetId() string { return v.Id }

// GetCreatedAt returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.CreatedAt, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetCreatedAt() string { return v.CreatedAt }

// GetUpdatedAt returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.UpdatedAt, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetUpdatedAt() string { return v.UpdatedAt }

// GetDeletedAt returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.DeletedAt, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetDeletedAt() string { return v.DeletedAt }

// GetToken returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.Token, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetToken() string { return v.Token }

// GetName returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.Name, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetName() string { return v.Name }

// GetDescription returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.Description, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetDescription() string {
	return v.Description
}

// GetImageUrl returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.ImageUrl, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetImageUrl() string { return v.ImageUrl }

// GetIcon returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.Icon, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetIcon() string { return v.Icon }

// GetBackgroundColor returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.BackgroundColor, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetBackgroundColor() string {
	return v.BackgroundColor
}

// GetForegroundColor returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.ForegroundColor, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetForegroundColor() string {
	return v.ForegroundColor
}

// GetBorderColor returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.BorderColor, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetBorderColor() string {
	return v.BorderColor
}

// GetMetadata returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.Metadata, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetMetadata() string { return v.Metadata }

// getDeviceTypeByTokenResponse is returned by getDeviceTypeByToken on success.
type getDeviceTypeByTokenResponse struct {
	DeviceTypeByToken getDeviceTypeByTokenDeviceTypeByTokenDeviceType `json:"deviceTypeByToken"`
}

// GetDeviceTypeByToken returns getDeviceTypeByTokenResponse.DeviceTypeByToken, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenResponse) GetDeviceTypeByToken() getDeviceTypeByTokenDeviceTypeByTokenDeviceType {
	return v.DeviceTypeByToken
}

// listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResults includes the requested fields of the GraphQL type DeviceRelationshipTypeSearchResults.
type listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResults struct {
	Results    []listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsResultsDeviceRelationshipType `json:"results"`
	Pagination listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsPagination                      `json:"pagination"`
}

// GetResults returns listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResults.Results, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResults) GetResults() []listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsResultsDeviceRelationshipType {
	return v.Results
}

// GetPagination returns listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResults.Pagination, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResults) GetPagination() listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsPagination {
	return v.Pagination
}

// listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsPagination includes the requested fields of the GraphQL type SearchResultsPagination.
type listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsPagination struct {
	PageStart    int `json:"pageStart"`
	PageEnd      int `json:"pageEnd"`
	TotalRecords int `json:"totalRecords"`
}

// GetPageStart returns listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsPagination.PageStart, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsPagination) GetPageStart() int {
	return v.PageStart
}

// GetPageEnd returns listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsPagination.PageEnd, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsPagination) GetPageEnd() int {
	return v.PageEnd
}

// GetTotalRecords returns listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsPagination.TotalRecords, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsPagination) GetTotalRecords() int {
	return v.TotalRecords
}

// listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsResultsDeviceRelationshipType includes the requested fields of the GraphQL type DeviceRelationshipType.
type listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsResultsDeviceRelationshipType struct {
	Id          string `json:"id"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
	DeletedAt   string `json:"deletedAt"`
	Token       string `json:"token"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Metadata    string `json:"metadata"`
}

// GetId returns listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsResultsDeviceRelationshipType.Id, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsResultsDeviceRelationshipType) GetId() string {
	return v.Id
}

// GetCreatedAt returns listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsResultsDeviceRelationshipType.CreatedAt, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsResultsDeviceRelationshipType) GetCreatedAt() string {
	return v.CreatedAt
}

// GetUpdatedAt returns listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsResultsDeviceRelationshipType.UpdatedAt, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsResultsDeviceRelationshipType) GetUpdatedAt() string {
	return v.UpdatedAt
}

// GetDeletedAt returns listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsResultsDeviceRelationshipType.DeletedAt, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsResultsDeviceRelationshipType) GetDeletedAt() string {
	return v.DeletedAt
}

// GetToken returns listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsResultsDeviceRelationshipType.Token, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsResultsDeviceRelationshipType) GetToken() string {
	return v.Token
}

// GetName returns listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsResultsDeviceRelationshipType.Name, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsResultsDeviceRelationshipType) GetName() string {
	return v.Name
}

// GetDescription returns listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsResultsDeviceRelationshipType.Description, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsResultsDeviceRelationshipType) GetDescription() string {
	return v.Description
}

// GetMetadata returns listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsResultsDeviceRelationshipType.Metadata, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResultsResultsDeviceRelationshipType) GetMetadata() string {
	return v.Metadata
}

// listDeviceRelationshipTypesResponse is returned by listDeviceRelationshipTypes on success.
type listDeviceRelationshipTypesResponse struct {
	DeviceRelationshipTypes listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResults `json:"deviceRelationshipTypes"`
}

// GetDeviceRelationshipTypes returns listDeviceRelationshipTypesResponse.DeviceRelationshipTypes, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipTypesResponse) GetDeviceRelationshipTypes() listDeviceRelationshipTypesDeviceRelationshipTypesDeviceRelationshipTypeSearchResults {
	return v.DeviceRelationshipTypes
}

// listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResults includes the requested fields of the GraphQL type DeviceRelationshipSearchResults.
type listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResults struct {
	Results    []listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationship `json:"results"`
	Pagination listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsPagination                  `json:"pagination"`
}

// GetResults returns listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResults.Results, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResults) GetResults() []listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationship {
	return v.Results
}

// GetPagination returns listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResults.Pagination, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResults) GetPagination() listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsPagination {
	return v.Pagination
}

// listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsPagination includes the requested fields of the GraphQL type SearchResultsPagination.
type listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsPagination struct {
	PageStart    int `json:"pageStart"`
	PageEnd      int `json:"pageEnd"`
	TotalRecords int `json:"totalRecords"`
}

// GetPageStart returns listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsPagination.PageStart, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsPagination) GetPageStart() int {
	return v.PageStart
}

// GetPageEnd returns listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsPagination.PageEnd, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsPagination) GetPageEnd() int {
	return v.PageEnd
}

// GetTotalRecords returns listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsPagination.TotalRecords, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsPagination) GetTotalRecords() int {
	return v.TotalRecords
}

// listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationship includes the requested fields of the GraphQL type DeviceRelationship.
type listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationship struct {
	Id               string                                                                                                                                   `json:"id"`
	SourceDevice     listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipSourceDevice                           `json:"sourceDevice"`
	TargetDevice     listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipTargetDevice                           `json:"targetDevice"`
	RelationshipType listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipRelationshipTypeDeviceRelationshipType `json:"relationshipType"`
	Metadata         string                                                                                                                                   `json:"metadata"`
}

// GetId returns listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationship.Id, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationship) GetId() string {
	return v.Id
}

// GetSourceDevice returns listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationship.SourceDevice, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationship) GetSourceDevice() listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipSourceDevice {
	return v.SourceDevice
}

// GetTargetDevice returns listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationship.TargetDevice, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationship) GetTargetDevice() listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipTargetDevice {
	return v.TargetDevice
}

// GetRelationshipType returns listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationship.RelationshipType, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationship) GetRelationshipType() listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipRelationshipTypeDeviceRelationshipType {
	return v.RelationshipType
}

// GetMetadata returns listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationship.Metadata, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationship) GetMetadata() string {
	return v.Metadata
}

// listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipRelationshipTypeDeviceRelationshipType includes the requested fields of the GraphQL type DeviceRelationshipType.
type listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipRelationshipTypeDeviceRelationshipType struct {
	Token       string `json:"token"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

// GetToken returns listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipRelationshipTypeDeviceRelationshipType.Token, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipRelationshipTypeDeviceRelationshipType) GetToken() string {
	return v.Token
}

// GetName returns listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipRelationshipTypeDeviceRelationshipType.Name, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipRelationshipTypeDeviceRelationshipType) GetName() string {
	return v.Name
}

// GetDescription returns listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipRelationshipTypeDeviceRelationshipType.Description, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipRelationshipTypeDeviceRelationshipType) GetDescription() string {
	return v.Description
}

// listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipSourceDevice includes the requested fields of the GraphQL type Device.
type listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipSourceDevice struct {
	Token       string `json:"token"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

// GetToken returns listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipSourceDevice.Token, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipSourceDevice) GetToken() string {
	return v.Token
}

// GetName returns listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipSourceDevice.Name, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipSourceDevice) GetName() string {
	return v.Name
}

// GetDescription returns listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipSourceDevice.Description, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipSourceDevice) GetDescription() string {
	return v.Description
}

// listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipTargetDevice includes the requested fields of the GraphQL type Device.
type listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipTargetDevice struct {
	Token       string `json:"token"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

// GetToken returns listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipTargetDevice.Token, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipTargetDevice) GetToken() string {
	return v.Token
}

// GetName returns listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipTargetDevice.Name, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipTargetDevice) GetName() string {
	return v.Name
}

// GetDescription returns listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipTargetDevice.Description, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResultsResultsDeviceRelationshipTargetDevice) GetDescription() string {
	return v.Description
}

// listDeviceRelationshipsResponse is returned by listDeviceRelationships on success.
type listDeviceRelationshipsResponse struct {
	DeviceRelationships listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResults `json:"deviceRelationships"`
}

// GetDeviceRelationships returns listDeviceRelationshipsResponse.DeviceRelationships, and is useful for accessing the field via an interface.
func (v *listDeviceRelationshipsResponse) GetDeviceRelationships() listDeviceRelationshipsDeviceRelationshipsDeviceRelationshipSearchResults {
	return v.DeviceRelationships
}

// listDeviceTypesDeviceTypesDeviceTypeSearchResults includes the requested fields of the GraphQL type DeviceTypeSearchResults.
type listDeviceTypesDeviceTypesDeviceTypeSearchResults struct {
	Results    []listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType `json:"results"`
	Pagination listDeviceTypesDeviceTypesDeviceTypeSearchResultsPagination          `json:"pagination"`
}

// GetResults returns listDeviceTypesDeviceTypesDeviceTypeSearchResults.Results, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResults) GetResults() []listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType {
	return v.Results
}

// GetPagination returns listDeviceTypesDeviceTypesDeviceTypeSearchResults.Pagination, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResults) GetPagination() listDeviceTypesDeviceTypesDeviceTypeSearchResultsPagination {
	return v.Pagination
}

// listDeviceTypesDeviceTypesDeviceTypeSearchResultsPagination includes the requested fields of the GraphQL type SearchResultsPagination.
type listDeviceTypesDeviceTypesDeviceTypeSearchResultsPagination struct {
	PageStart    int `json:"pageStart"`
	PageEnd      int `json:"pageEnd"`
	TotalRecords int `json:"totalRecords"`
}

// GetPageStart returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsPagination.PageStart, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsPagination) GetPageStart() int {
	return v.PageStart
}

// GetPageEnd returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsPagination.PageEnd, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsPagination) GetPageEnd() int {
	return v.PageEnd
}

// GetTotalRecords returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsPagination.TotalRecords, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsPagination) GetTotalRecords() int {
	return v.TotalRecords
}

// listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType includes the requested fields of the GraphQL type DeviceType.
type listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType struct {
	Id              string `json:"id"`
	CreatedAt       string `json:"createdAt"`
	UpdatedAt       string `json:"updatedAt"`
	DeletedAt       string `json:"deletedAt"`
	Token           string `json:"token"`
	Name            string `json:"name"`
	Description     string `json:"description"`
	ImageUrl        string `json:"imageUrl"`
	Icon            string `json:"icon"`
	BackgroundColor string `json:"backgroundColor"`
	ForegroundColor string `json:"foregroundColor"`
	BorderColor     string `json:"borderColor"`
	Metadata        string `json:"metadata"`
}

// GetId returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.Id, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetId() string {
	return v.Id
}

// GetCreatedAt returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.CreatedAt, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetCreatedAt() string {
	return v.CreatedAt
}

// GetUpdatedAt returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.UpdatedAt, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetUpdatedAt() string {
	return v.UpdatedAt
}

// GetDeletedAt returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.DeletedAt, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetDeletedAt() string {
	return v.DeletedAt
}

// GetToken returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.Token, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetToken() string {
	return v.Token
}

// GetName returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.Name, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetName() string {
	return v.Name
}

// GetDescription returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.Description, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetDescription() string {
	return v.Description
}

// GetImageUrl returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.ImageUrl, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetImageUrl() string {
	return v.ImageUrl
}

// GetIcon returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.Icon, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetIcon() string {
	return v.Icon
}

// GetBackgroundColor returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.BackgroundColor, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetBackgroundColor() string {
	return v.BackgroundColor
}

// GetForegroundColor returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.ForegroundColor, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetForegroundColor() string {
	return v.ForegroundColor
}

// GetBorderColor returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.BorderColor, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetBorderColor() string {
	return v.BorderColor
}

// GetMetadata returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.Metadata, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetMetadata() string {
	return v.Metadata
}

// listDeviceTypesResponse is returned by listDeviceTypes on success.
type listDeviceTypesResponse struct {
	DeviceTypes listDeviceTypesDeviceTypesDeviceTypeSearchResults `json:"deviceTypes"`
}

// GetDeviceTypes returns listDeviceTypesResponse.DeviceTypes, and is useful for accessing the field via an interface.
func (v *listDeviceTypesResponse) GetDeviceTypes() listDeviceTypesDeviceTypesDeviceTypeSearchResults {
	return v.DeviceTypes
}

// listDevicesDevicesDeviceSearchResults includes the requested fields of the GraphQL type DeviceSearchResults.
type listDevicesDevicesDeviceSearchResults struct {
	Results    []listDevicesDevicesDeviceSearchResultsResultsDevice `json:"results"`
	Pagination listDevicesDevicesDeviceSearchResultsPagination      `json:"pagination"`
}

// GetResults returns listDevicesDevicesDeviceSearchResults.Results, and is useful for accessing the field via an interface.
func (v *listDevicesDevicesDeviceSearchResults) GetResults() []listDevicesDevicesDeviceSearchResultsResultsDevice {
	return v.Results
}

// GetPagination returns listDevicesDevicesDeviceSearchResults.Pagination, and is useful for accessing the field via an interface.
func (v *listDevicesDevicesDeviceSearchResults) GetPagination() listDevicesDevicesDeviceSearchResultsPagination {
	return v.Pagination
}

// listDevicesDevicesDeviceSearchResultsPagination includes the requested fields of the GraphQL type SearchResultsPagination.
type listDevicesDevicesDeviceSearchResultsPagination struct {
	PageStart    int `json:"pageStart"`
	PageEnd      int `json:"pageEnd"`
	TotalRecords int `json:"totalRecords"`
}

// GetPageStart returns listDevicesDevicesDeviceSearchResultsPagination.PageStart, and is useful for accessing the field via an interface.
func (v *listDevicesDevicesDeviceSearchResultsPagination) GetPageStart() int { return v.PageStart }

// GetPageEnd returns listDevicesDevicesDeviceSearchResultsPagination.PageEnd, and is useful for accessing the field via an interface.
func (v *listDevicesDevicesDeviceSearchResultsPagination) GetPageEnd() int { return v.PageEnd }

// GetTotalRecords returns listDevicesDevicesDeviceSearchResultsPagination.TotalRecords, and is useful for accessing the field via an interface.
func (v *listDevicesDevicesDeviceSearchResultsPagination) GetTotalRecords() int {
	return v.TotalRecords
}

// listDevicesDevicesDeviceSearchResultsResultsDevice includes the requested fields of the GraphQL type Device.
type listDevicesDevicesDeviceSearchResultsResultsDevice struct {
	Id                string                                                                                `json:"id"`
	CreatedAt         string                                                                                `json:"createdAt"`
	UpdatedAt         string                                                                                `json:"updatedAt"`
	DeletedAt         string                                                                                `json:"deletedAt"`
	Token             string                                                                                `json:"token"`
	Name              string                                                                                `json:"name"`
	Description       string                                                                                `json:"description"`
	DeviceType        listDevicesDevicesDeviceSearchResultsResultsDeviceDeviceType                          `json:"deviceType"`
	ActiveAssignments []listDevicesDevicesDeviceSearchResultsResultsDeviceActiveAssignmentsDeviceAssignment `json:"activeAssignments"`
	Metadata          string                                                                                `json:"metadata"`
}

// GetId returns listDevicesDevicesDeviceSearchResultsResultsDevice.Id, and is useful for accessing the field via an interface.
func (v *listDevicesDevicesDeviceSearchResultsResultsDevice) GetId() string { return v.Id }

// GetCreatedAt returns listDevicesDevicesDeviceSearchResultsResultsDevice.CreatedAt, and is useful for accessing the field via an interface.
func (v *listDevicesDevicesDeviceSearchResultsResultsDevice) GetCreatedAt() string {
	return v.CreatedAt
}

// GetUpdatedAt returns listDevicesDevicesDeviceSearchResultsResultsDevice.UpdatedAt, and is useful for accessing the field via an interface.
func (v *listDevicesDevicesDeviceSearchResultsResultsDevice) GetUpdatedAt() string {
	return v.UpdatedAt
}

// GetDeletedAt returns listDevicesDevicesDeviceSearchResultsResultsDevice.DeletedAt, and is useful for accessing the field via an interface.
func (v *listDevicesDevicesDeviceSearchResultsResultsDevice) GetDeletedAt() string {
	return v.DeletedAt
}

// GetToken returns listDevicesDevicesDeviceSearchResultsResultsDevice.Token, and is useful for accessing the field via an interface.
func (v *listDevicesDevicesDeviceSearchResultsResultsDevice) GetToken() string { return v.Token }

// GetName returns listDevicesDevicesDeviceSearchResultsResultsDevice.Name, and is useful for accessing the field via an interface.
func (v *listDevicesDevicesDeviceSearchResultsResultsDevice) GetName() string { return v.Name }

// GetDescription returns listDevicesDevicesDeviceSearchResultsResultsDevice.Description, and is useful for accessing the field via an interface.
func (v *listDevicesDevicesDeviceSearchResultsResultsDevice) GetDescription() string {
	return v.Description
}

// GetDeviceType returns listDevicesDevicesDeviceSearchResultsResultsDevice.DeviceType, and is useful for accessing the field via an interface.
func (v *listDevicesDevicesDeviceSearchResultsResultsDevice) GetDeviceType() listDevicesDevicesDeviceSearchResultsResultsDeviceDeviceType {
	return v.DeviceType
}

// GetActiveAssignments returns listDevicesDevicesDeviceSearchResultsResultsDevice.ActiveAssignments, and is useful for accessing the field via an interface.
func (v *listDevicesDevicesDeviceSearchResultsResultsDevice) GetActiveAssignments() []listDevicesDevicesDeviceSearchResultsResultsDeviceActiveAssignmentsDeviceAssignment {
	return v.ActiveAssignments
}

// GetMetadata returns listDevicesDevicesDeviceSearchResultsResultsDevice.Metadata, and is useful for accessing the field via an interface.
func (v *listDevicesDevicesDeviceSearchResultsResultsDevice) GetMetadata() string { return v.Metadata }

// listDevicesDevicesDeviceSearchResultsResultsDeviceActiveAssignmentsDeviceAssignment includes the requested fields of the GraphQL type DeviceAssignment.
type listDevicesDevicesDeviceSearchResultsResultsDeviceActiveAssignmentsDeviceAssignment struct {
	Token string `json:"token"`
}

// GetToken returns listDevicesDevicesDeviceSearchResultsResultsDeviceActiveAssignmentsDeviceAssignment.Token, and is useful for accessing the field via an interface.
func (v *listDevicesDevicesDeviceSearchResultsResultsDeviceActiveAssignmentsDeviceAssignment) GetToken() string {
	return v.Token
}

// listDevicesDevicesDeviceSearchResultsResultsDeviceDeviceType includes the requested fields of the GraphQL type DeviceType.
type listDevicesDevicesDeviceSearchResultsResultsDeviceDeviceType struct {
	Token       string `json:"token"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

// GetToken returns listDevicesDevicesDeviceSearchResultsResultsDeviceDeviceType.Token, and is useful for accessing the field via an interface.
func (v *listDevicesDevicesDeviceSearchResultsResultsDeviceDeviceType) GetToken() string {
	return v.Token
}

// GetName returns listDevicesDevicesDeviceSearchResultsResultsDeviceDeviceType.Name, and is useful for accessing the field via an interface.
func (v *listDevicesDevicesDeviceSearchResultsResultsDeviceDeviceType) GetName() string {
	return v.Name
}

// GetDescription returns listDevicesDevicesDeviceSearchResultsResultsDeviceDeviceType.Description, and is useful for accessing the field via an interface.
func (v *listDevicesDevicesDeviceSearchResultsResultsDeviceDeviceType) GetDescription() string {
	return v.Description
}

// listDevicesResponse is returned by listDevices on success.
type listDevicesResponse struct {
	Devices listDevicesDevicesDeviceSearchResults `json:"devices"`
}

// GetDevices returns listDevicesResponse.Devices, and is useful for accessing the field via an interface.
func (v *listDevicesResponse) GetDevices() listDevicesDevicesDeviceSearchResults { return v.Devices }

// Create device and return identifiers.
func createDevice(
	ctx context.Context,
	client graphql.Client,
	token string,
	deviceTypeToken string,
	name string,
	description string,
	metadata string,
) (*createDeviceResponse, error) {
	__input := __createDeviceInput{
		Token:           token,
		DeviceTypeToken: deviceTypeToken,
		Name:            name,
		Description:     description,
		Metadata:        metadata,
	}
	var err error

	var retval createDeviceResponse
	err = client.MakeRequest(
		ctx,
		"createDevice",
		`
mutation createDevice ($token: String!, $deviceTypeToken: String!, $name: String, $description: String, $metadata: String) {
	createDevice(request: {token:$token,deviceTypeToken:$deviceTypeToken,name:$name,description:$description,metadata:$metadata}) {
		id
		token
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

// Create device relationship and return identifiers.
func createDeviceRelationship(
	ctx context.Context,
	client graphql.Client,
	token string,
	sourceDevice string,
	targetDevice string,
	relationshipType string,
) (*createDeviceRelationshipResponse, error) {
	__input := __createDeviceRelationshipInput{
		Token:            token,
		SourceDevice:     sourceDevice,
		TargetDevice:     targetDevice,
		RelationshipType: relationshipType,
	}
	var err error

	var retval createDeviceRelationshipResponse
	err = client.MakeRequest(
		ctx,
		"createDeviceRelationship",
		`
mutation createDeviceRelationship ($token: String!, $sourceDevice: String!, $targetDevice: String!, $relationshipType: String!) {
	createDeviceRelationship(request: {token:$token,sourceDevice:$sourceDevice,targetDevice:$targetDevice,relationshipType:$relationshipType}) {
		id
		token
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

// Create device relationship type and return identifiers.
func createDeviceRelationshipType(
	ctx context.Context,
	client graphql.Client,
	token string,
	name string,
	description string,
	metadata string,
) (*createDeviceRelationshipTypeResponse, error) {
	__input := __createDeviceRelationshipTypeInput{
		Token:       token,
		Name:        name,
		Description: description,
		Metadata:    metadata,
	}
	var err error

	var retval createDeviceRelationshipTypeResponse
	err = client.MakeRequest(
		ctx,
		"createDeviceRelationshipType",
		`
mutation createDeviceRelationshipType ($token: String!, $name: String, $description: String, $metadata: String) {
	createDeviceRelationshipType(request: {token:$token,name:$name,description:$description,metadata:$metadata}) {
		id
		token
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

// Create device type and return identifiers.
func createDeviceType(
	ctx context.Context,
	client graphql.Client,
	token string,
	name string,
	description string,
	imageUrl string,
	icon string,
	backgroundColor string,
	foregroundColor string,
	borderColor string,
	metadata string,
) (*createDeviceTypeResponse, error) {
	__input := __createDeviceTypeInput{
		Token:           token,
		Name:            name,
		Description:     description,
		ImageUrl:        imageUrl,
		Icon:            icon,
		BackgroundColor: backgroundColor,
		ForegroundColor: foregroundColor,
		BorderColor:     borderColor,
		Metadata:        metadata,
	}
	var err error

	var retval createDeviceTypeResponse
	err = client.MakeRequest(
		ctx,
		"createDeviceType",
		`
mutation createDeviceType ($token: String!, $name: String, $description: String, $imageUrl: String, $icon: String, $backgroundColor: String, $foregroundColor: String, $borderColor: String, $metadata: String) {
	createDeviceType(request: {token:$token,name:$name,description:$description,imageUrl:$imageUrl,icon:$icon,backgroundColor:$backgroundColor,foregroundColor:$foregroundColor,borderColor:$borderColor,metadata:$metadata}) {
		id
		token
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

// Get device by unique token.
func getDeviceByToken(
	ctx context.Context,
	client graphql.Client,
	token string,
) (*getDeviceByTokenResponse, error) {
	__input := __getDeviceByTokenInput{
		Token: token,
	}
	var err error

	var retval getDeviceByTokenResponse
	err = client.MakeRequest(
		ctx,
		"getDeviceByToken",
		`
query getDeviceByToken ($token: String!) {
	deviceByToken(token: $token) {
		id
		createdAt
		updatedAt
		deletedAt
		token
		name
		description
		deviceType {
			token
			name
			description
		}
		activeAssignments {
			token
		}
		metadata
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

// Get device relationship by unique token.
func getDeviceRelationshipByToken(
	ctx context.Context,
	client graphql.Client,
	token string,
) (*getDeviceRelationshipByTokenResponse, error) {
	__input := __getDeviceRelationshipByTokenInput{
		Token: token,
	}
	var err error

	var retval getDeviceRelationshipByTokenResponse
	err = client.MakeRequest(
		ctx,
		"getDeviceRelationshipByToken",
		`
query getDeviceRelationshipByToken ($token: String!) {
	deviceRelationshipByToken(token: $token) {
		id
		createdAt
		updatedAt
		deletedAt
		token
		sourceDevice {
			token
			name
			description
		}
		targetDevice {
			token
			name
			description
		}
		relationshipType {
			token
			name
			description
		}
		metadata
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

// Get device relationship type by unique token.
func getDeviceRelationshipTypeByToken(
	ctx context.Context,
	client graphql.Client,
	token string,
) (*getDeviceRelationshipTypeByTokenResponse, error) {
	__input := __getDeviceRelationshipTypeByTokenInput{
		Token: token,
	}
	var err error

	var retval getDeviceRelationshipTypeByTokenResponse
	err = client.MakeRequest(
		ctx,
		"getDeviceRelationshipTypeByToken",
		`
query getDeviceRelationshipTypeByToken ($token: String!) {
	deviceRelationshipTypeByToken(token: $token) {
		id
		createdAt
		updatedAt
		deletedAt
		token
		name
		description
		metadata
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

// Get device type by unique token.
func getDeviceTypeByToken(
	ctx context.Context,
	client graphql.Client,
	token string,
) (*getDeviceTypeByTokenResponse, error) {
	__input := __getDeviceTypeByTokenInput{
		Token: token,
	}
	var err error

	var retval getDeviceTypeByTokenResponse
	err = client.MakeRequest(
		ctx,
		"getDeviceTypeByToken",
		`
query getDeviceTypeByToken ($token: String!) {
	deviceTypeByToken(token: $token) {
		id
		createdAt
		updatedAt
		deletedAt
		token
		name
		description
		imageUrl
		icon
		backgroundColor
		foregroundColor
		borderColor
		metadata
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

// List device relationship types that match criteria.
func listDeviceRelationshipTypes(
	ctx context.Context,
	client graphql.Client,
	pageNumber int,
	pageSize int,
) (*listDeviceRelationshipTypesResponse, error) {
	__input := __listDeviceRelationshipTypesInput{
		PageNumber: pageNumber,
		PageSize:   pageSize,
	}
	var err error

	var retval listDeviceRelationshipTypesResponse
	err = client.MakeRequest(
		ctx,
		"listDeviceRelationshipTypes",
		`
query listDeviceRelationshipTypes ($pageNumber: Int!, $pageSize: Int!) {
	deviceRelationshipTypes(criteria: {pageNumber:$pageNumber,pageSize:$pageSize}) {
		results {
			id
			createdAt
			updatedAt
			deletedAt
			token
			name
			description
			metadata
		}
		pagination {
			pageStart
			pageEnd
			totalRecords
		}
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

// List device relationship types that match criteria.
func listDeviceRelationships(
	ctx context.Context,
	client graphql.Client,
	pageNumber int,
	pageSize int,
) (*listDeviceRelationshipsResponse, error) {
	__input := __listDeviceRelationshipsInput{
		PageNumber: pageNumber,
		PageSize:   pageSize,
	}
	var err error

	var retval listDeviceRelationshipsResponse
	err = client.MakeRequest(
		ctx,
		"listDeviceRelationships",
		`
query listDeviceRelationships ($pageNumber: Int!, $pageSize: Int!) {
	deviceRelationships(criteria: {pageNumber:$pageNumber,pageSize:$pageSize}) {
		results {
			id
			sourceDevice {
				token
				name
				description
			}
			targetDevice {
				token
				name
				description
			}
			relationshipType {
				token
				name
				description
			}
			metadata
		}
		pagination {
			pageStart
			pageEnd
			totalRecords
		}
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

// List device types that match criteria.
func listDeviceTypes(
	ctx context.Context,
	client graphql.Client,
	pageNumber int,
	pageSize int,
) (*listDeviceTypesResponse, error) {
	__input := __listDeviceTypesInput{
		PageNumber: pageNumber,
		PageSize:   pageSize,
	}
	var err error

	var retval listDeviceTypesResponse
	err = client.MakeRequest(
		ctx,
		"listDeviceTypes",
		`
query listDeviceTypes ($pageNumber: Int!, $pageSize: Int!) {
	deviceTypes(criteria: {pageNumber:$pageNumber,pageSize:$pageSize}) {
		results {
			id
			createdAt
			updatedAt
			deletedAt
			token
			name
			description
			imageUrl
			icon
			backgroundColor
			foregroundColor
			borderColor
			metadata
		}
		pagination {
			pageStart
			pageEnd
			totalRecords
		}
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

// List devices that match criteria.
func listDevices(
	ctx context.Context,
	client graphql.Client,
	pageNumber int,
	pageSize int,
) (*listDevicesResponse, error) {
	__input := __listDevicesInput{
		PageNumber: pageNumber,
		PageSize:   pageSize,
	}
	var err error

	var retval listDevicesResponse
	err = client.MakeRequest(
		ctx,
		"listDevices",
		`
query listDevices ($pageNumber: Int!, $pageSize: Int!) {
	devices(criteria: {pageNumber:$pageNumber,pageSize:$pageSize}) {
		results {
			id
			createdAt
			updatedAt
			deletedAt
			token
			name
			description
			deviceType {
				token
				name
				description
			}
			activeAssignments {
				token
			}
			metadata
		}
		pagination {
			pageStart
			pageEnd
			totalRecords
		}
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}
