// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package gqlclient

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// __createDeviceTypeInput is used internally by genqlient
type __createDeviceTypeInput struct {
	Token           string `json:"token"`
	Name            string `json:"name"`
	Description     string `json:"description"`
	ImageUrl        string `json:"imageUrl"`
	Icon            string `json:"icon"`
	BackgroundColor string `json:"backgroundColor"`
	ForegroundColor string `json:"foregroundColor"`
	BorderColor     string `json:"borderColor"`
	Metadata        string `json:"metadata"`
}

// GetToken returns __createDeviceTypeInput.Token, and is useful for accessing the field via an interface.
func (v *__createDeviceTypeInput) GetToken() string { return v.Token }

// GetName returns __createDeviceTypeInput.Name, and is useful for accessing the field via an interface.
func (v *__createDeviceTypeInput) GetName() string { return v.Name }

// GetDescription returns __createDeviceTypeInput.Description, and is useful for accessing the field via an interface.
func (v *__createDeviceTypeInput) GetDescription() string { return v.Description }

// GetImageUrl returns __createDeviceTypeInput.ImageUrl, and is useful for accessing the field via an interface.
func (v *__createDeviceTypeInput) GetImageUrl() string { return v.ImageUrl }

// GetIcon returns __createDeviceTypeInput.Icon, and is useful for accessing the field via an interface.
func (v *__createDeviceTypeInput) GetIcon() string { return v.Icon }

// GetBackgroundColor returns __createDeviceTypeInput.BackgroundColor, and is useful for accessing the field via an interface.
func (v *__createDeviceTypeInput) GetBackgroundColor() string { return v.BackgroundColor }

// GetForegroundColor returns __createDeviceTypeInput.ForegroundColor, and is useful for accessing the field via an interface.
func (v *__createDeviceTypeInput) GetForegroundColor() string { return v.ForegroundColor }

// GetBorderColor returns __createDeviceTypeInput.BorderColor, and is useful for accessing the field via an interface.
func (v *__createDeviceTypeInput) GetBorderColor() string { return v.BorderColor }

// GetMetadata returns __createDeviceTypeInput.Metadata, and is useful for accessing the field via an interface.
func (v *__createDeviceTypeInput) GetMetadata() string { return v.Metadata }

// __getDeviceTypeByIdInput is used internally by genqlient
type __getDeviceTypeByIdInput struct {
	Id string `json:"id"`
}

// GetId returns __getDeviceTypeByIdInput.Id, and is useful for accessing the field via an interface.
func (v *__getDeviceTypeByIdInput) GetId() string { return v.Id }

// __getDeviceTypeByTokenInput is used internally by genqlient
type __getDeviceTypeByTokenInput struct {
	Token string `json:"token"`
}

// GetToken returns __getDeviceTypeByTokenInput.Token, and is useful for accessing the field via an interface.
func (v *__getDeviceTypeByTokenInput) GetToken() string { return v.Token }

// __listDeviceTypesInput is used internally by genqlient
type __listDeviceTypesInput struct {
	PageNumber int `json:"pageNumber"`
	PageSize   int `json:"pageSize"`
}

// GetPageNumber returns __listDeviceTypesInput.PageNumber, and is useful for accessing the field via an interface.
func (v *__listDeviceTypesInput) GetPageNumber() int { return v.PageNumber }

// GetPageSize returns __listDeviceTypesInput.PageSize, and is useful for accessing the field via an interface.
func (v *__listDeviceTypesInput) GetPageSize() int { return v.PageSize }

// createDeviceTypeCreateDeviceType includes the requested fields of the GraphQL type DeviceType.
type createDeviceTypeCreateDeviceType struct {
	Id    string `json:"id"`
	Token string `json:"token"`
}

// GetId returns createDeviceTypeCreateDeviceType.Id, and is useful for accessing the field via an interface.
func (v *createDeviceTypeCreateDeviceType) GetId() string { return v.Id }

// GetToken returns createDeviceTypeCreateDeviceType.Token, and is useful for accessing the field via an interface.
func (v *createDeviceTypeCreateDeviceType) GetToken() string { return v.Token }

// createDeviceTypeResponse is returned by createDeviceType on success.
type createDeviceTypeResponse struct {
	CreateDeviceType createDeviceTypeCreateDeviceType `json:"createDeviceType"`
}

// GetCreateDeviceType returns createDeviceTypeResponse.CreateDeviceType, and is useful for accessing the field via an interface.
func (v *createDeviceTypeResponse) GetCreateDeviceType() createDeviceTypeCreateDeviceType {
	return v.CreateDeviceType
}

// getDeviceTypeByIdDeviceType includes the requested fields of the GraphQL type DeviceType.
type getDeviceTypeByIdDeviceType struct {
	Id              string `json:"id"`
	CreatedAt       string `json:"createdAt"`
	UpdatedAt       string `json:"updatedAt"`
	DeletedAt       string `json:"deletedAt"`
	Token           string `json:"token"`
	Name            string `json:"name"`
	Description     string `json:"description"`
	ImageUrl        string `json:"imageUrl"`
	Icon            string `json:"icon"`
	BackgroundColor string `json:"backgroundColor"`
	ForegroundColor string `json:"foregroundColor"`
	BorderColor     string `json:"borderColor"`
	Metadata        string `json:"metadata"`
}

// GetId returns getDeviceTypeByIdDeviceType.Id, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByIdDeviceType) GetId() string { return v.Id }

// GetCreatedAt returns getDeviceTypeByIdDeviceType.CreatedAt, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByIdDeviceType) GetCreatedAt() string { return v.CreatedAt }

// GetUpdatedAt returns getDeviceTypeByIdDeviceType.UpdatedAt, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByIdDeviceType) GetUpdatedAt() string { return v.UpdatedAt }

// GetDeletedAt returns getDeviceTypeByIdDeviceType.DeletedAt, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByIdDeviceType) GetDeletedAt() string { return v.DeletedAt }

// GetToken returns getDeviceTypeByIdDeviceType.Token, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByIdDeviceType) GetToken() string { return v.Token }

// GetName returns getDeviceTypeByIdDeviceType.Name, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByIdDeviceType) GetName() string { return v.Name }

// GetDescription returns getDeviceTypeByIdDeviceType.Description, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByIdDeviceType) GetDescription() string { return v.Description }

// GetImageUrl returns getDeviceTypeByIdDeviceType.ImageUrl, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByIdDeviceType) GetImageUrl() string { return v.ImageUrl }

// GetIcon returns getDeviceTypeByIdDeviceType.Icon, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByIdDeviceType) GetIcon() string { return v.Icon }

// GetBackgroundColor returns getDeviceTypeByIdDeviceType.BackgroundColor, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByIdDeviceType) GetBackgroundColor() string { return v.BackgroundColor }

// GetForegroundColor returns getDeviceTypeByIdDeviceType.ForegroundColor, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByIdDeviceType) GetForegroundColor() string { return v.ForegroundColor }

// GetBorderColor returns getDeviceTypeByIdDeviceType.BorderColor, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByIdDeviceType) GetBorderColor() string { return v.BorderColor }

// GetMetadata returns getDeviceTypeByIdDeviceType.Metadata, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByIdDeviceType) GetMetadata() string { return v.Metadata }

// getDeviceTypeByIdResponse is returned by getDeviceTypeById on success.
type getDeviceTypeByIdResponse struct {
	DeviceType getDeviceTypeByIdDeviceType `json:"deviceType"`
}

// GetDeviceType returns getDeviceTypeByIdResponse.DeviceType, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByIdResponse) GetDeviceType() getDeviceTypeByIdDeviceType { return v.DeviceType }

// getDeviceTypeByTokenDeviceTypeByTokenDeviceType includes the requested fields of the GraphQL type DeviceType.
type getDeviceTypeByTokenDeviceTypeByTokenDeviceType struct {
	Id              string `json:"id"`
	CreatedAt       string `json:"createdAt"`
	UpdatedAt       string `json:"updatedAt"`
	DeletedAt       string `json:"deletedAt"`
	Token           string `json:"token"`
	Name            string `json:"name"`
	Description     string `json:"description"`
	ImageUrl        string `json:"imageUrl"`
	Icon            string `json:"icon"`
	BackgroundColor string `json:"backgroundColor"`
	ForegroundColor string `json:"foregroundColor"`
	BorderColor     string `json:"borderColor"`
	Metadata        string `json:"metadata"`
}

// GetId returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.Id, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetId() string { return v.Id }

// GetCreatedAt returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.CreatedAt, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetCreatedAt() string { return v.CreatedAt }

// GetUpdatedAt returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.UpdatedAt, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetUpdatedAt() string { return v.UpdatedAt }

// GetDeletedAt returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.DeletedAt, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetDeletedAt() string { return v.DeletedAt }

// GetToken returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.Token, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetToken() string { return v.Token }

// GetName returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.Name, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetName() string { return v.Name }

// GetDescription returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.Description, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetDescription() string {
	return v.Description
}

// GetImageUrl returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.ImageUrl, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetImageUrl() string { return v.ImageUrl }

// GetIcon returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.Icon, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetIcon() string { return v.Icon }

// GetBackgroundColor returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.BackgroundColor, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetBackgroundColor() string {
	return v.BackgroundColor
}

// GetForegroundColor returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.ForegroundColor, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetForegroundColor() string {
	return v.ForegroundColor
}

// GetBorderColor returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.BorderColor, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetBorderColor() string {
	return v.BorderColor
}

// GetMetadata returns getDeviceTypeByTokenDeviceTypeByTokenDeviceType.Metadata, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenDeviceTypeByTokenDeviceType) GetMetadata() string { return v.Metadata }

// getDeviceTypeByTokenResponse is returned by getDeviceTypeByToken on success.
type getDeviceTypeByTokenResponse struct {
	DeviceTypeByToken getDeviceTypeByTokenDeviceTypeByTokenDeviceType `json:"deviceTypeByToken"`
}

// GetDeviceTypeByToken returns getDeviceTypeByTokenResponse.DeviceTypeByToken, and is useful for accessing the field via an interface.
func (v *getDeviceTypeByTokenResponse) GetDeviceTypeByToken() getDeviceTypeByTokenDeviceTypeByTokenDeviceType {
	return v.DeviceTypeByToken
}

// listDeviceTypesDeviceTypesDeviceTypeSearchResults includes the requested fields of the GraphQL type DeviceTypeSearchResults.
type listDeviceTypesDeviceTypesDeviceTypeSearchResults struct {
	Results []listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType `json:"results"`
}

// GetResults returns listDeviceTypesDeviceTypesDeviceTypeSearchResults.Results, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResults) GetResults() []listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType {
	return v.Results
}

// listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType includes the requested fields of the GraphQL type DeviceType.
type listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType struct {
	Id              string `json:"id"`
	CreatedAt       string `json:"createdAt"`
	UpdatedAt       string `json:"updatedAt"`
	DeletedAt       string `json:"deletedAt"`
	Token           string `json:"token"`
	Name            string `json:"name"`
	Description     string `json:"description"`
	ImageUrl        string `json:"imageUrl"`
	Icon            string `json:"icon"`
	BackgroundColor string `json:"backgroundColor"`
	ForegroundColor string `json:"foregroundColor"`
	BorderColor     string `json:"borderColor"`
	Metadata        string `json:"metadata"`
}

// GetId returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.Id, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetId() string {
	return v.Id
}

// GetCreatedAt returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.CreatedAt, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetCreatedAt() string {
	return v.CreatedAt
}

// GetUpdatedAt returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.UpdatedAt, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetUpdatedAt() string {
	return v.UpdatedAt
}

// GetDeletedAt returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.DeletedAt, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetDeletedAt() string {
	return v.DeletedAt
}

// GetToken returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.Token, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetToken() string {
	return v.Token
}

// GetName returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.Name, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetName() string {
	return v.Name
}

// GetDescription returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.Description, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetDescription() string {
	return v.Description
}

// GetImageUrl returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.ImageUrl, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetImageUrl() string {
	return v.ImageUrl
}

// GetIcon returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.Icon, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetIcon() string {
	return v.Icon
}

// GetBackgroundColor returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.BackgroundColor, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetBackgroundColor() string {
	return v.BackgroundColor
}

// GetForegroundColor returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.ForegroundColor, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetForegroundColor() string {
	return v.ForegroundColor
}

// GetBorderColor returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.BorderColor, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetBorderColor() string {
	return v.BorderColor
}

// GetMetadata returns listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType.Metadata, and is useful for accessing the field via an interface.
func (v *listDeviceTypesDeviceTypesDeviceTypeSearchResultsResultsDeviceType) GetMetadata() string {
	return v.Metadata
}

// listDeviceTypesResponse is returned by listDeviceTypes on success.
type listDeviceTypesResponse struct {
	DeviceTypes listDeviceTypesDeviceTypesDeviceTypeSearchResults `json:"deviceTypes"`
}

// GetDeviceTypes returns listDeviceTypesResponse.DeviceTypes, and is useful for accessing the field via an interface.
func (v *listDeviceTypesResponse) GetDeviceTypes() listDeviceTypesDeviceTypesDeviceTypeSearchResults {
	return v.DeviceTypes
}

// Create device type and return identifiers.
func createDeviceType(
	ctx context.Context,
	client graphql.Client,
	token string,
	name string,
	description string,
	imageUrl string,
	icon string,
	backgroundColor string,
	foregroundColor string,
	borderColor string,
	metadata string,
) (*createDeviceTypeResponse, error) {
	__input := __createDeviceTypeInput{
		Token:           token,
		Name:            name,
		Description:     description,
		ImageUrl:        imageUrl,
		Icon:            icon,
		BackgroundColor: backgroundColor,
		ForegroundColor: foregroundColor,
		BorderColor:     borderColor,
		Metadata:        metadata,
	}
	var err error

	var retval createDeviceTypeResponse
	err = client.MakeRequest(
		ctx,
		"createDeviceType",
		`
mutation createDeviceType ($token: String!, $name: String, $description: String, $imageUrl: String, $icon: String, $backgroundColor: String, $foregroundColor: String, $borderColor: String, $metadata: String) {
	createDeviceType(request: {token:$token,name:$name,description:$description,imageUrl:$imageUrl,icon:$icon,backgroundColor:$backgroundColor,foregroundColor:$foregroundColor,borderColor:$borderColor,metadata:$metadata}) {
		id
		token
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

// Get device type by unique internal id.
func getDeviceTypeById(
	ctx context.Context,
	client graphql.Client,
	id string,
) (*getDeviceTypeByIdResponse, error) {
	__input := __getDeviceTypeByIdInput{
		Id: id,
	}
	var err error

	var retval getDeviceTypeByIdResponse
	err = client.MakeRequest(
		ctx,
		"getDeviceTypeById",
		`
query getDeviceTypeById ($id: ID!) {
	deviceType(id: $id) {
		id
		createdAt
		updatedAt
		deletedAt
		token
		name
		description
		imageUrl
		icon
		backgroundColor
		foregroundColor
		borderColor
		metadata
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

// Get device type by unique token.
func getDeviceTypeByToken(
	ctx context.Context,
	client graphql.Client,
	token string,
) (*getDeviceTypeByTokenResponse, error) {
	__input := __getDeviceTypeByTokenInput{
		Token: token,
	}
	var err error

	var retval getDeviceTypeByTokenResponse
	err = client.MakeRequest(
		ctx,
		"getDeviceTypeByToken",
		`
query getDeviceTypeByToken ($token: String!) {
	deviceTypeByToken(token: $token) {
		id
		createdAt
		updatedAt
		deletedAt
		token
		name
		description
		imageUrl
		icon
		backgroundColor
		foregroundColor
		borderColor
		metadata
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

// List device types that match criteria.
func listDeviceTypes(
	ctx context.Context,
	client graphql.Client,
	pageNumber int,
	pageSize int,
) (*listDeviceTypesResponse, error) {
	__input := __listDeviceTypesInput{
		PageNumber: pageNumber,
		PageSize:   pageSize,
	}
	var err error

	var retval listDeviceTypesResponse
	err = client.MakeRequest(
		ctx,
		"listDeviceTypes",
		`
query listDeviceTypes ($pageNumber: Int!, $pageSize: Int!) {
	deviceTypes(criteria: {pageNumber:$pageNumber,pageSize:$pageSize}) {
		results {
			id
			createdAt
			updatedAt
			deletedAt
			token
			name
			description
			imageUrl
			icon
			backgroundColor
			foregroundColor
			borderColor
			metadata
		}
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}
