
# Represents a type or class of devices
type DeviceType implements Model & TokenReference & NamedEntity & BrandedEntity {
    id: ID!
    created_at: String
    updated_at: String
    deleted_at: String
    token: String!
    name: String
    description: String
    imageUrl: String
    icon: String
    backgroundColor: String
    foregroundColor: String
    borderColor: String
}

# Data required to create a device type.
input DeviceTypeCreateRequest {
    token: String!
    name: String
    description: String
    imageUrl: String
    icon: String
    backgroundColor: String
    foregroundColor: String
    borderColor: String
}

# Criteria used when searching for device types.
input DeviceTypeSearchCriteria {
    pageNumber: Int!
    pageSize: Int!
}

# Represents a device instance
type Device implements Model & TokenReference & NamedEntity {
    id: ID!
    created_at: String
    updated_at: String
    deleted_at: String
    token: String!
    name: String
    description: String
    deviceType: DeviceType!
}

# Data required to create a device.
input DeviceCreateRequest {
    token: String!
    name: String
    description: String
    deviceTypeToken: String!
}

# Criteria used when searching for devices.
input DeviceSearchCriteria {
    pageNumber: Int!
    pageSize: Int!
    deviceTypeToken: String
}

# Represents a type of relation between devices.
type DeviceRelationshipType implements Model & TokenReference & NamedEntity {
    id: ID!
    created_at: String
    updated_at: String
    deleted_at: String
    token: String!
    name: String
    description: String
}

# Data required to create a device relationship type.
input DeviceRelationshipTypeCreateRequest {
    token: String!
    name: String
    description: String
}

# Criteria used when searching for device relationship types.
input DeviceRelationshipTypeSearchCriteria {
    pageNumber: Int!
    pageSize: Int!
}

# Represents a relationship between devices.
type DeviceRelationship implements Model {
    id: ID!
    created_at: String
    updated_at: String
    deleted_at: String
    sourceDevice: Device!
    targetDevice: Device!
    relationshipType: DeviceRelationshipType!
}

# Data required to create a device relationship.
input DeviceRelationshipCreateRequest {
    sourceDevice: String!
    targetDevice: String!
    relationshipType: String!
}

# Criteria used when searching for device relationships.
input DeviceRelationshipSearchCriteria {
    pageNumber: Int!
    pageSize: Int!
}

# Contains queries executed against model.
type Query {
    # Find a device type by unique id.
    deviceType(id: ID!): DeviceType!
    # Find a device type by unique token.
    deviceTypeByToken(token: String!): DeviceType!
    # List devices that meet criteria.
    deviceTypes(criteria: DeviceTypeSearchCriteria!): [DeviceType!]!
    # Find a device by unique id.
    device(id: ID!): Device!
    # Find a device by unique token.
    deviceByToken(token: String!): Device!
    # List devices that meet criteria.
    devices(criteria: DeviceSearchCriteria!): [Device!]!
    # Find a device relationship type by unique id.
    deviceRelationshipType(id: ID!): DeviceRelationshipType!
    # Find a device relationship type by unique token.
    deviceRelationshipTypeByToken(token: String!): DeviceRelationshipType!
    # List device relationship types that meet criteria.
    deviceRelationshipTypes(criteria: DeviceRelationshipTypeSearchCriteria!): [DeviceRelationshipType!]!
    # Find a device relationship by unique id.
    deviceRelationship(id: ID!): DeviceRelationship!
    # List device relationships that meet criteria.
    deviceRelationships(criteria: DeviceRelationshipSearchCriteria!): [DeviceRelationship!]!
}

# Contains mutations executed against model.
type Mutation {
    # Create a new device type.
    createDeviceType(value: DeviceTypeCreateRequest): DeviceType!
    # Update an existing device type.
    updateDeviceType(token: String!, value: DeviceTypeCreateRequest): DeviceType!
    # Create a new device.
    createDevice(value: DeviceCreateRequest): Device!
    # Update an existing device.
    updateDevice(token: String!, value: DeviceCreateRequest): Device!
    # Create a new device relationship type.
    createDeviceRelationshipType(value: DeviceRelationshipTypeCreateRequest): DeviceRelationshipType!
    # Update an existing device relationship type.
    updateDeviceRelationshipType(token: String!, value: DeviceRelationshipTypeCreateRequest): DeviceRelationshipType!
    # Create a new device relationship.
    createDeviceRelationship(value: DeviceRelationshipCreateRequest): DeviceRelationship!
}

schema {
    query: Query
    mutation: Mutation
}
